// Generated by CoffeeScript 1.6.3
var byCollection, resultsByAssessmentId;

byCollection = function(doc) {
  if (doc.collection) {
    return emit(doc.collection, doc);
  }
};

resultsByAssessmentId = function(doc) {
  var id;
  if (doc.collection !== 'result') {
    return;
  }
  id = doc.assessmentId || doc.klassId;
  return emit(id, null);
};
