// Generated by CoffeeScript 1.6.3
var resultsByAssessmentId;

resultsByAssessmentId = function(doc) {
  var id;
  if (doc.collection !== 'result') {
    return;
  }
  id = doc.assessmentId || doc.klassId;
  return emit(id, null);
};
